spring:
  datasource:
    url: jdbc:oracle:thin:@wvudatabase.czc0zuhxihvw.us-east-1.rds.amazonaws.com:1521:orcl
    username: JuneBestBatch
    password: p4ssw0rd
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: false
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
server:
  port: 0
